# Bloodborne DroidDeck mobile defaults.
upscaler=fsr3
preset=2
sharpen=1
sharpness=0.50
object_motion=1
show_fps=1
output_res=1280x720
model_lod=0
live_resolution=0
effect_chromatic_aberration=0
effect_dof=0
effect_motion_blur=0
effect_ssao=1
effect_game_aa=1
effect_dynamic_shadows=1
effect_ssr=0
skip_intro=0
debug_camera=0
debug_menu=0
