# Driverless rootfs/proot package for aarch64 bbport targets. It intentionally
# excludes Vulkan GPU drivers; users import Linux/rootfs drivers into BB_DATA_DIR.
{ pkgs ? import <nixpkgs> { }
  # Store paths used by prebuilt bbport ELF RUNPATHs, generated by runtime-tar.sh.
, runtimePaths ? (if builtins.pathExists ./runtime-paths.nix then import ./runtime-paths.nix else [ ])
}:
let
  lib = pkgs.lib;
  arm = pkgs.stdenv.hostPlatform.isAarch64;
  root = ./..;
in
if !arm then
  throw "driverless runtime tar packaging must be built for an aarch64-linux host/runner"
else
let
  src = builtins.path {
    name = "bbport-runtime-src";
    path = root;
    filter = path: type:
      let
        rel = lib.removePrefix (toString root + "/") (toString path);
        includeDir = dir: rel == dir || lib.hasPrefix (dir + "/") rel;
      in builtins.elem rel [ "run.sh" ]
        || lib.any includeDir [ "scripts" "patches" ];
  };
  python = pkgs.python3;
  runtimeStorePaths = map builtins.storePath runtimePaths;
  runtimeLibPath = lib.makeLibraryPath ([ pkgs.vulkan-loader pkgs.libglvnd pkgs.libx11 pkgs.libxext ]
    ++ runtimeStorePaths);
  runtimePath = lib.makeBinPath [
    pkgs.bash
    pkgs.coreutils
    pkgs.gnugrep
    pkgs.gnused
    pkgs.procps
    pkgs.util-linux
  ];
  # External Vulkan drivers (Turnip and friends) are imported by the user and resolve their
  # DT_NEEDED entirely through LD_LIBRARY_PATH (their ICDs carry no RUNPATH). Ship the common
  # driver dependencies in a stable compat/ directory so an imported driver needs no manual
  # library-path setup, and keep them on the same nix glibc as the runtime so they are never
  # mixed with the base rootfs's older copies (which broke Turnip with a missing
  # wl_fixes_interface and libxkbcommon V_1.10.0).
  compatLibs = [
    pkgs.wayland
    pkgs.zlib
    pkgs.zstd
    pkgs.libdrm
    pkgs.libxcb
    pkgs.libX11
    pkgs.libxkbcommon
    pkgs.libxshmfence
    pkgs.stdenv.cc.cc.lib
    pkgs.glibc
  ];
in
pkgs.stdenv.mkDerivation {
  pname = "bbport-runtime-rootfs";
  version = "0.1";
  inherit src;
  buildInputs = [ pkgs.vulkan-loader pkgs.vulkan-tools ] ++ runtimeStorePaths ++ compatLibs;
  dontBuild = true;
  dontConfigure = true;
  dontPatchELF = true;
  dontWrapGApps = true;

  installPhase = ''
    runHook preInstall
    d=$out/opt/bbport/share/bbport
    mkdir -p $d/bin/gpu $d/bin/cpu $out/opt/bbport/bin

    cp run.sh $d/
    cp -r scripts patches $d/
    install -m755 ${../out/bb-probe} $d/bin/bb-probe
    install -m755 ${../out/bb-gpu-capabilities} $d/bin/bb-gpu-capabilities
    install -m755 ${../out/gpu/libbbgpu.so} $d/bin/gpu/libbbgpu.so
    install -m755 ${../out/fex/libbbcpu.so} $d/bin/cpu/libbbcpu.so

    substitute ${./runtime-run.sh} $out/opt/bbport/bin/bbport \
      --replace-fail @PYTHON@ ${python}/bin/python3 \
      --replace-fail @PATH@ ${runtimePath} \
      --replace-fail @LD_LIBRARY_PATH@ ${runtimeLibPath} \
      --replace-fail @VULKANINFO@ ${pkgs.vulkan-tools}/bin/vulkaninfo \
      --replace-fail @BASH@ ${pkgs.bash}/bin/bash
    chmod +x $out/opt/bbport/bin/bbport

    substitute ${./runtime-driver.sh} $out/opt/bbport/bin/bbport-driver \
      --replace-fail @PYTHON@ ${python}/bin/python3
    chmod +x $out/opt/bbport/bin/bbport-driver

    # compat/: driver dependency search directory. The entry wrapper puts it first on
    # LD_LIBRARY_PATH so an imported Linux/Turnip ICD loads with no user configuration.
    compat=$d/compat
    mkdir -p $compat
    link_compat() {
        local dir=$1; shift
        local g f
        for g in "$@"; do
            for f in $dir/$g; do
                [ -e "$f" ] && ln -sf "$f" $compat/ || true
            done
        done
    }
    link_compat ${pkgs.wayland}/lib 'libwayland-client.so*' 'libwayland-egl.so*'
    link_compat ${pkgs.zlib}/lib 'libz.so*'
    link_compat ${pkgs.zstd}/lib 'libzstd.so*'
    link_compat ${pkgs.libdrm}/lib 'libdrm.so*'
    link_compat ${pkgs.libxcb}/lib 'libxcb.so*' 'libxcb-*.so*'
    link_compat ${pkgs.libX11}/lib 'libX11-xcb.so*'
    link_compat ${pkgs.libxkbcommon}/lib 'libxkbcommon.so*' 'libxkbcommon-x11.so*' 'libxkbregistry.so*'
    link_compat ${pkgs.libxshmfence}/lib 'libxshmfence.so*'
    link_compat ${pkgs.stdenv.cc.cc.lib}/lib 'libstdc++.so*'
    link_compat ${pkgs.glibc}/lib 'libc.so.6'

    cat > $out/opt/bbport/README-runtime-tar.txt <<'DOC'
bbport driverless runtime package

Install/extract this archive as a rootfs/proot overlay. Import a Linux/rootfs
Vulkan driver before launching:

  /opt/bbport/bin/bbport-driver import /path/to/linux-driver.zip
  BB_GAME_DIR=/path/to/CUSA03173 /opt/bbport/bin/bbport

The default driver store is $BB_DATA_DIR/drivers. Android/AdrenoTools-only
driver packages are not Linux/rootfs Vulkan ICD drivers and are rejected by the
import command.

The /opt/bbport/bin/bbport wrapper enables BB_ANDROID_ROOTFS_PROFILE=1 by
default. Set BB_ANDROID_ROOTFS_PROFILE=0 for the plain runtime defaults, or set
individual BB_* variables to override the profile. Keep BB_GAME_DIR,
BB_DATA_DIR, shader cache and imported drivers on fast rootfs storage rather
than /sdcard or other FUSE-backed paths.

This package intentionally excludes Vulkan GPU drivers, the GTK launcher,
Steam/AppImage entrypoints, MangoHud, FSR asset directories and FSR
asset-building tools.
DOC
    runHook postInstall
  '';
}
