# Minimal rootfs/proot package for aarch64 Turnip targets. This intentionally
# does not include the GTK launcher, Steam/AppImage entrypoints, MangoHud, FSR
# assets, or FSR asset-building tools.
{ pkgs ? import <nixpkgs> { }
  # Store paths used by prebuilt bbport ELF RUNPATHs, generated by turnip-tar.sh.
, runtimePaths ? (if builtins.pathExists ./runtime-paths.nix then import ./runtime-paths.nix else [ ])
}:
let
  lib = pkgs.lib;
  arm = pkgs.stdenv.hostPlatform.isAarch64;
  root = ./..;
in
if !arm then
  throw "minimal Turnip tar packaging must be built for an aarch64-linux host/runner"
else
let
  src = builtins.path {
    name = "bbport-minimal-src";
    path = root;
    filter = path: type:
      let
        rel = lib.removePrefix (toString root + "/") (toString path);
        includeDir = dir: rel == dir || lib.hasPrefix (dir + "/") rel;
      in builtins.elem rel [ "run.sh" ]
        || lib.any includeDir [ "scripts" "patches" ];
  };
  turnip = (pkgs.mesa.override {
    galliumDrivers = [ "freedreno" ];
    vulkanDrivers = [ "freedreno" ];
    vulkanLayers = [ ];
    enablePatentEncumberedCodecs = false;
  }).overrideAttrs (old: {
    patches = old.patches ++ [
      ./mesa-sm8550/0001-add-a830-chip-id.patch
      ./mesa-sm8550/0001-freedreno-ir3-vulkan-disable-bindless-ubo-const-lowering.patch
      ./mesa-sm8550/001-fix-freedreno-vulkan.patch
    ];
    mesonFlags = map (flag: if lib.hasPrefix "-Dtools=" flag then "-Dtools=" else flag) old.mesonFlags
      ++ [ "-Dgallium-va=disabled" ];
    postInstall = old.postInstall + ''
      mkdir -p $opencl $spirv2dxil
    '';
  });
  icdArch = pkgs.stdenv.hostPlatform.parsed.cpu.name;
  turnipIcd = "${turnip}/share/vulkan/icd.d/freedreno_icd.${icdArch}.json";
  python = pkgs.python3;
  runtimeStorePaths = map builtins.storePath runtimePaths;
  runtimeLibPath = lib.makeLibraryPath ([ pkgs.vulkan-loader pkgs.libglvnd pkgs.libx11 pkgs.libxext ]
    ++ runtimeStorePaths);
  runtimePath = lib.makeBinPath [
    pkgs.bash
    pkgs.coreutils
    pkgs.gnugrep
    pkgs.gnused
    pkgs.procps
    pkgs.util-linux
  ];
in
pkgs.stdenv.mkDerivation {
  pname = "bbport-turnip-rootfs";
  version = "0.1";
  inherit src;
  buildInputs = [ pkgs.vulkan-loader turnip ] ++ runtimeStorePaths;
  dontBuild = true;
  dontConfigure = true;
  dontPatchELF = true;
  dontWrapGApps = true;

  installPhase = ''
    runHook preInstall
    d=$out/opt/bbport/share/bbport
    mkdir -p $d/bin/gpu $d/bin/cpu $out/opt/bbport/bin

    cp run.sh $d/
    cp -r scripts patches $d/
    install -m755 ${../out/bb-probe} $d/bin/bb-probe
    install -m755 ${../out/bb-gpu-capabilities} $d/bin/bb-gpu-capabilities
    install -m755 ${../out/gpu/libbbgpu.so} $d/bin/gpu/libbbgpu.so
    install -m755 ${../out/fex/libbbcpu.so} $d/bin/cpu/libbbcpu.so

    substitute ${./turnip-run.sh} $out/opt/bbport/bin/bbport-turnip \
      --replace-fail @PYTHON@ ${python}/bin/python3 \
      --replace-fail @PATH@ ${runtimePath} \
      --replace-fail @LD_LIBRARY_PATH@ ${runtimeLibPath} \
      --replace-fail @TURNIP_ICD@ ${turnipIcd} \
      --replace-fail @VULKANINFO@ ${pkgs.vulkan-tools}/bin/vulkaninfo \
      --replace-fail @BASH@ ${pkgs.bash}/bin/bash
    chmod +x $out/opt/bbport/bin/bbport-turnip

    cat > $out/opt/bbport/README-turnip-tar.txt <<'DOC'
bbport minimal Turnip tar package

Install/extract this archive as a rootfs/proot overlay. The default command is:

  /opt/bbport/bin/bbport-turnip

Set BB_GAME_DIR to your Bloodborne CUSA03173 v1.09 dump and BB_DATA_DIR to a
writable directory for generated files, saves, settings and caches.

This package intentionally excludes the GTK launcher, Steam/AppImage entrypoints,
MangoHud, FSR asset directories and FSR asset-building tools.
DOC
    runHook postInstall
  '';

  passthru = { inherit turnip turnipIcd; };
}
