#!/usr/bin/env python3
"""Generates gpu/shim/bbport_gnm_table.inc: the eboot's libGnm functions the engine calls, with a
relocatable prologue (whole instructions >= 5 bytes, no RIP-relative operands or branches) for the
call census hooks (BB_GNM_CENSUS) and, later, their replacements.

Usage: gen_gnm_table.py region.asm gnm_cg.txt gnm_sigs.txt > gpu/shim/bbport_gnm_table.inc
(region.asm: objdump -D -b binary -m i386:x86-64 -M intel --insn-width=16 of the extracted text, 0x1068000-0x10a0000;
gnm_cg.txt: tools/re/callgraph.py; gnm_sigs.txt: tools/re/gnm_sigs.py)
"""
import re, sys

ins = re.compile(r'^\s*([0-9a-f]+):\t((?:[0-9a-f]{2} )+)\s*\t(.*)$')
UNSAFE = ('rip', 'call', 'jmp', 'ret', 'j', 'loop', 'int3', '(bad)')

def main():
    code = {}
    order = []
    for line in open(sys.argv[1]):
        m = ins.match(line)
        if not m:
            continue
        a = int(m.group(1), 16)
        code[a] = (bytes.fromhex(m.group(2).replace(' ', '')), m.group(3).strip())
        order.append(a)
    sigs = {}
    for line in open(sys.argv[3]):
        head, _, sig = line.partition(': ')
        sigs[int(head.split()[0], 16)] = sig.strip()
    names = {}
    import os
    names_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gnm_names.txt')
    for line in open(names_path):
        line = line.split('#', 1)[0].split()
        if len(line) >= 2:
            names[int(line[0], 16)] = line[1]
    rows = []
    skipped = 0
    for line in open(sys.argv[2]):
        p = line.split()
        fn, size, sites, ext = int(p[0], 16), int(p[2]), int(p[4]), int(p[6])
        if size < 16:
            continue
        # Command buffer methods are hooked even when only libGnm itself calls them (a caller in
        # Gnmx may not be hooked); other functions only when the engine calls them.
        cb = any(re.search(r'call\s+QWORD PTR \[r\w+\+0x18\]', code[x][1])
                 for x in range(fn, fn + size) if x in code)
        if ext == 0 and not cb:
            continue
        a, pro, ok = fn, b'', True
        while len(pro) < 5:
            if a not in code:
                ok = False
                break
            b, text = code[a]
            mnem = text.split()[0] if text else '(bad)'
            if 'rip' in text or mnem.startswith('j') or mnem in ('call', 'ret', 'loop', 'int3', '(bad)') or a >= fn + size:
                ok = False
                break
            pro += b
            a += len(b)
        if not ok or len(pro) > 15:
            skipped += 1
            continue
        name = (sigs.get(fn) or '').replace('"', "'")[:120]
        if fn in names:
            name = names[fn] + (': ' + name if name else '')
        rows.append((fn, pro, sites, name, cb))
    print('// Generated by tools/re/gen_gnm_table.py from the CUSA03173 1.09 eboot: the libGnm functions')
    print('// the engine calls (offset, prologue bytes moved into the hook stub, static call sites,')
    print('// command buffer method: calls the reserve callback, PM4 immediates).')
    print(f'// {len(rows)} functions; {skipped} skipped (prologue not relocatable).')
    for fn, pro, sites, name, cb in rows:
        bs = ', '.join(f'0x{x:02x}' for x in pro)
        print(f'{{0x{fn:x}, {len(pro)}, {{{bs}}}, {sites}, {int(cb)}, "{name}"}},')

main()
